FROM node:16-alpine AS builder
WORKDIR "/app"
COPY . /app
RUN npm ci --force
RUN npm run build
RUN npm prune --production


FROM node:16-alpine AS production
WORKDIR "/app"
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json
COPY --from=builder /app/dist /app/dist
RUN npm install serve -g
EXPOSE 3000
CMD ["serve", "-s", "dist"]





